/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface JubJubInterface extends ethers.utils.Interface {
  functions: {
    "COFACTOR()": FunctionFragment;
    "JUBJUB_A()": FunctionFragment;
    "JUBJUB_D()": FunctionFragment;
    "L()": FunctionFragment;
    "Q()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "COFACTOR", values?: undefined): string;
  encodeFunctionData(functionFragment: "JUBJUB_A", values?: undefined): string;
  encodeFunctionData(functionFragment: "JUBJUB_D", values?: undefined): string;
  encodeFunctionData(functionFragment: "L", values?: undefined): string;
  encodeFunctionData(functionFragment: "Q", values?: undefined): string;

  decodeFunctionResult(functionFragment: "COFACTOR", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "JUBJUB_A", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "JUBJUB_D", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "L", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Q", data: BytesLike): Result;

  events: {};
}

export class JubJub extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: JubJubInterface;

  functions: {
    COFACTOR(overrides?: CallOverrides): Promise<[BigNumber]>;

    JUBJUB_A(overrides?: CallOverrides): Promise<[BigNumber]>;

    JUBJUB_D(overrides?: CallOverrides): Promise<[BigNumber]>;

    L(overrides?: CallOverrides): Promise<[BigNumber]>;

    Q(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  COFACTOR(overrides?: CallOverrides): Promise<BigNumber>;

  JUBJUB_A(overrides?: CallOverrides): Promise<BigNumber>;

  JUBJUB_D(overrides?: CallOverrides): Promise<BigNumber>;

  L(overrides?: CallOverrides): Promise<BigNumber>;

  Q(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    COFACTOR(overrides?: CallOverrides): Promise<BigNumber>;

    JUBJUB_A(overrides?: CallOverrides): Promise<BigNumber>;

    JUBJUB_D(overrides?: CallOverrides): Promise<BigNumber>;

    L(overrides?: CallOverrides): Promise<BigNumber>;

    Q(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    COFACTOR(overrides?: CallOverrides): Promise<BigNumber>;

    JUBJUB_A(overrides?: CallOverrides): Promise<BigNumber>;

    JUBJUB_D(overrides?: CallOverrides): Promise<BigNumber>;

    L(overrides?: CallOverrides): Promise<BigNumber>;

    Q(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    COFACTOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    JUBJUB_A(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    JUBJUB_D(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    L(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    Q(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
